#Write a program to perform atleast 20 operations on string
a="Hello there!"
b='how are you'
print(a+b)
print(a*5)
print(a.lower())
print(b.upper())
print(b.capitalize())
print(a.count("l"))
print(b.find('o'))
print(id(a))
print(len(b))
print(a.swapcase())
print(b.title())
print(a.index('o'))
print(a==b)
print('a' in 'apha')
print('a' not in 'apha')
print(type(a))
print(int(input('what ur age')))
print(a.isdecimal())
print(b.isascii())
print(a.isalpha())
print(a.format)
print(b.isalnum())
